# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Triggering Api Tests
      run: curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${{secrets.API_TEST_SECRET}}" https://api.github.com/repos/SainiRenuka/TestDummy/dispatches -d '{"event_type":"custom_event_type"}'
